spring:
  datasource:
    url: jdbc:mysql://localhost:3306/superherosightingtest?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19970829